apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: label-injector-webhook
webhooks:
  - name: label-injector.example.com
    clientConfig:
      # Use a direct URL with http:// instead of a 'service:' reference
      url: "http://label-injector-service.default.svc.cluster.local:8080/mutate"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    # Keep the same objectSelector (if you want the same scoping as before)
    objectSelector:
      matchExpressions:
        - key: rollouts-pod-template-hash
          operator: Exists
    admissionReviewVersions: ["v1"]
    sideEffects: None
