apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: label-injector-webhook
webhooks:
  - name: label-injector.example.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: label-injector-service
        namespace: default
        path: /mutate
        port: 8443
      insecureSkipTLSVerify: true
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    objectSelector:
      matchExpressions:
        - key: rollouts-pod-template-hash
          operator: Exists

