apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout-app
spec:
  project: default
  source:
    repoURL: https://github.com/David-SerranoA/argo-test 
    path: .
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
