apiVersion: v1
kind: Service
metadata:
  name: label-injector-service
  namespace: default
  labels:
    app: label-injector
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8443
  selector:
    app: label-injector
